import type { Evidence } from '@/domain/evidence';
import type { NormalizedVideoCandidate } from '@/domain/video';
import type { DetectionContext } from '@/domain/evidence';
import type { Detector } from '../engine';

/**
 * AI-discussion context detector.
 *
 * Produces *opposing* evidence when the title indicates the video is ABOUT
 * AI rather than generated BY it ("How AI works", "AI regulation explained",
 * "I tested Sora", "Why AI-generated videos are everywhere"). This is the
 * primary false-positive guard required by the spec — a video discussing AI
 * is not automatically AI-generated.
 */
const DISCUSSION_PATTERNS: readonly { re: RegExp; text: string }[] = [
  {
    re: /\bhow\s+(do(es)?\s+|to\s+understand\s+)?(generative\s+)?A\.?I\.?\s+(works?|thinks?|learns?)\b/i,
    text: 'The title explains how AI works — this is a discussion, not generated content.',
  },
  {
    re: /\b(what|why)\s+(is|are)\s+(generative\s+)?A\.?I\.?\b/i,
    text: 'The title asks about AI as a topic.',
  },
  {
    re: /\bA\.?I\.?\s+(explained|documentary(?!.*generated)|news|report|analysis|debate|hearing)\b/i,
    text: 'The title indicates news or analysis about AI.',
  },
  {
    re: /\bA\.?I\.?\s+slop\b/i,
    text: 'The title discusses AI slop as a topic, which is commentary rather than generated content.',
  },
  {
    re: /\bI\s+(tested|reviewed|tried)\b[^.!?]{0,40}?\b(sora|veo|chat\s?gpt|gemini|midjourney|an?\s+A\.?I\.?\s+(tool|generator|video))\b/i,
    text: 'The title suggests a human test or review of AI tools.',
  },
  {
    re: /\b(sora|veo|chat\s?gpt|gemini|midjourney)\s+(explained|review|tutorial|guide|tips|demo)\b/i,
    text: 'The title is a review or explainer of an AI tool.',
  },
  {
    re: /\b(tutorial|explained|explainer|guide)\b.*\b(A\.?I\.?|sora|veo|gemini|chat\s?gpt)\b/i,
    text: 'The title looks like a tutorial or explainer about AI tools.',
  },
  {
    re: /\bwhy\s+A\.?I\.?\s+(slop|videos?|content)\s+(is|are)\s+(everywhere|ruining|taking\s+over)\b/i,
    text: 'The title is commentary about AI slop itself.',
  },
  {
    re: /\b(artificial\s+intelligence|A\.?I\.?)\s+(regulation|hearing|laws?|bill|policy|summit|safety|risks?|dangers?)\b/i,
    text: 'The title refers to AI policy or risk topics.',
  },
  {
    re: /\b(dangers?|risks?|impact|future|ethics)\s+of\s+(artificial\s+intelligence|A\.?I\.?)\b/i,
    text: 'The title discusses risks or impact of AI as a topic.',
  },
  {
    re: /\bartificial\s+intelligence\s+(lecture|course|class|explained)\b/i,
    text: 'The title indicates educational AI content.',
  },
];

export const aiDiscussionDetector: Detector = {
  id: 'ai-discussion',
  detect(candidate: NormalizedVideoCandidate, _context: DetectionContext): Evidence[] {
    const evidence: Evidence[] = [];
    for (const { re, text } of DISCUSSION_PATTERNS) {
      if (re.test(candidate.title)) {
        evidence.push({
          id: 'discussion:context',
          origin: 'local-rule',
          category: 'ai-discussion',
          detector: 'ai-discussion',
          strength: 0.6,
          polarity: 'opposes',
          reasonCode: 'ai-discussion-context',
          reasonText: text,
        });
        break; // one strong opposing signal is enough
      }
    }
    return evidence;
  },
};
